---
- name: Create Local Admin User
  hosts: windows
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3 -W ignore::DeprecationWarning"
  tasks:
    - name: Create a new local user
      ansible.windows.win_user:
        name: "ubn_admin"
        password: "Oyin@abc123!"
        state: present
        groups:
          - Users
        password_never_expires: true

    - name: Add user to Administrators group
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - ubn_admin
        state: present
