---
- name: Test Connection Rulebook
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 1
  rules:
    - name: Trigger Job on Controller
      condition: event.i == 0
      action:
        run_job_template:
          name: "Demo Job Template" # Replace with the name of a real template on your controller
          organization: "Default"
