---
- name: Install PuTTY on Windows Server
  hosts: windows
  gather_facts: no

  tasks:

    - name: Download PuTTY MSI
      ansible.windows.win_get_url:
        url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.80-installer.msi
        dest: C:\Temp\putty.msi

    - name: Install PuTTY MSI
      ansible.windows.win_package:
        path: C:\Temp\putty.msi
        state: present
