- name: Install PuTTY on Windows Server using Chocolatey
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Ensure Chocolatey is installed (if not already)
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present

    - name: Install PuTTY via Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: putty
        state: present
