---
- name: Register RHEL hosts to Red Hat Satellite
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Clean existing subscription-manager data
      ansible.builtin.command: subscription-manager clean

    - name: Dynamically generate the registration command from Satellite
      redhat.satellite.registration_command:
        # These variables are automatically supplied by the AAP Credential:
        server_url: "{{ lookup('ansible.builtin.env', 'sat_server_url') }}"
        username: "{{ lookup('ansible.builtin.env', 'sat_username') }}"
        password: "{{ lookup('ansible.builtin.env', 'sat_password') }}"
        validate_certs: true
        organization: "1"
        location: "2"
        activation_keys:
          - "rhel10"
      delegate_to: localhost
      become: false
      register: sat_registration

    - name: Execute dynamic registration script on host
      ansible.builtin.shell:
        cmd: "{{ sat_registration.registration_command }}"
      args:
        executable: /bin/bash
      register: registration
      no_log: true
