---
- name: Register RHEL hosts to Red Hat Satellite
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: Clean existing subscription-manager data
      ansible.builtin.command:
        cmd: subscription-manager clean

    - name: Generate Satellite registration command
      redhat.satellite.registration_command:
        server_url: "{{ lookup('env','FOREMAN_SERVER_URL') }}"
        username: "{{ lookup('env','FOREMAN_USERNAME') }}"
        password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
        validate_certs: true
        organization: "1"
        location: "2"
        activation_keys:
          - rhel10
      delegate_to: localhost
      become: false
      register: sat_registration

    - name: Execute registration
      ansible.builtin.shell:
        cmd: "{{ sat_registration.registration_command }}"
      args:
        executable: /bin/bash
      register: registration
      no_log: true

    - name: Show registration result
      ansible.builtin.debug:
        var: registration.stdout_lines
