---
- name: Register RHEL hosts to Red Hat Satellite
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Clean existing subscription-manager data
      ansible.builtin.command:
        cmd: subscription-manager clean

    - name: Set Satellite activation key based on RHEL version
      ansible.builtin.set_fact:
        satellite_activation_key: "rhel{{ ansible_distribution_major_version }}"

    - name: Generate registration command from Red Hat Satellite
      redhat.satellite.registration_command:
        server_url: "{{ lookup('ansible.builtin.env', 'FOREMAN_SERVER_URL') }}"
        username: "{{ lookup('ansible.builtin.env', 'FOREMAN_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'FOREMAN_PASSWORD') }}"
        validate_certs: false
        organization: "TENECE"
        location: "SINARI"
        activation_keys:
          - "{{ satellite_activation_key }}"
      delegate_to: localhost
      become: false
      register: sat_registration

    - name: Execute Satellite registration command
      ansible.builtin.shell:
        cmd: "{{ sat_registration.registration_command }}"
      args:
        executable: /bin/bash
      register: registration
      no_log: true

    - name: Display registration output
      ansible.builtin.debug:
        var: registration.stdout_lines
